name: build armv7
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Commit on the given branch to build'
        required: true

jobs:
  build:
    name: 'ARMv7 engines build on tag ${{ github.event.inputs.tag }}'
    env:
      SQLITE_MAX_VARIABLE_NUMBER: 250000
      SQLITE_MAX_EXPR_DEPTH: 10000
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.event.inputs.tag }}
        uses: actions/checkout@v2
        with:
          repository: 'prisma/prisma-engines'
          ref: ${{ github.event.inputs.tag }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup cross with OpenSSL
        run: |-
          cat <<EOF > Cross.toml
            [target.armv7-unknown-linux-gnueabihf]
            pre-build = [
              "dpkg --add-architecture armhf",
              "apt-get update",
              "apt-get install -y curl git build-essential",
              "apt-get install -y libc6-armhf-cross libc6-dev-armhf-cross gcc-arm-linux-gnueabihf"
            ]
          EOF

      - name: List files for verification
        run: ls -al && cat Cross.toml

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-gnueabihf --release

      - uses: ncipollo/release-action@v1
        with:
          tag: 5.2.6
          commit: main
          token: ${{ secrets.GITHUB_TOKEN }}
          body: 'Automatic release via CI: ${{ github.event.inputs.tag }}'
          artifacts: |
            ${{ github.workspace }}/target/armv7-unknown-linux-gnueabihf/release/schema-engine,
            ${{ github.workspace }}/target/armv7-unknown-linux-gnueabihf/release/prisma-fmt,
            ${{ github.workspace }}/target/armv7-unknown-linux-gnueabihf/release/query-engine,
            ${{ github.workspace }}/target/armv7-unknown-linux-gnueabihf/release/psl,
